<?xml version="1.0" encoding="utf-8"?><Database Name="HumaneSociety" Class="HumaneSocietyDbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-PFNG8F3;Initial Catalog=HumaneSociety;Integrated Security=True" SettingsObjectName="HumaneSocietyFinal.Properties.Settings" SettingsPropertyName="HumaneSocietyConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Adopter" Member="Adopters">
    <Type Name="Adopter">
      <Column Name="AdopterID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Budget" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="HaveChildren" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="HousingEnvironment" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AnimalTypePreference" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AnimalSizePreference" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="age" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Animal" Member="Animals">
    <Type Name="Animal">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AnimalWeight" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AnimalType" Type="System.String" DbType="VarChar(75)" CanBeNull="true" />
      <Column Name="HasShots" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RoomNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="Cost" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Adopted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </Type>
  </Table>
</Database>